apiVersion: apps/v1
kind: Deployment
metadata:
  name: ysuier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ysuier
  template:
    metadata:
      labels:
        app: ysuier
    spec:
      containers:
      - image: okteto.dev/ysuier:latest
        name: ysuier
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "96cdda00-a13d-43a6-9756-72368c53eda4"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "96cdda00-a13d-43a6-9756-72368c53eda4"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
